import Link from "next/link";
import { Semaforo } from "../components/image";
import Head from "next/head";


export default function Home() {


  return (

    <div>
      <Head>
        <title>HelenK</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
        <Semaforo />
      </header>
      <main className="main">
        <h1>La seguridad siempre está en tus manos</h1>
        <br />
        <p>Hacé de tu viaje en las calles una experiencia agradable</p>
      </main>
      <main className="bottom-main">
        <div className="carr">
          <p id="button_1" className="button_carrousel"></p>
          <p id="button_2" className="button_carrousel"></p>
          <p id="button_3" className="button_carrousel"></p>
        </div>
      </main>
      <footer className="footer">
        <nav className="Navbar">
          
          <Link href="/register" className="link" passHref>
            <p className="NavbarLink">Regístrate</p>
          </Link>
          <Link href="/login" className="link" passHref>
            <p className="NavbarLink">Iniciar Sesión</p>
          </Link>
        </nav>
      </footer>
    </div>
  );
}


// import { signIn, signOut, useSession } from "next-auth/react";
// import Head from "next/head";
// import Link from "next/link";
// import { api } from "~/utils/api";

// export default function Home() {
//   const hello = api.example.hello.useQuery({ text: "from tRPC" });
//
//   return (
//     <>
//       <Head>
//         <title>HelenK</title>
//         <meta name="description" content="Generated by create-t3-app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
//         <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
//           <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
//             {/* <p className="text-2xl text-white">
//               {hello.data ? hello.data.greeting : "Loading tRPC query..."}
//             </p> */}
//           </div>
//         </div>
//       </main>
//     </>
//   );
// }


